/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category:
    "ad-byrja" | "matarraedi" | "ad-halda-afram" | "taekni" | "endurheimt";
  excerpt: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ExerciseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "exercise";
};

export type TrainingPlan = {
  _id: string;
  _type: "trainingPlan";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  goal: "fitutap" | "vodvauppbygging";
  sessionsPerWeek: 1 | 2 | 3 | 4 | 5;
  intro?: string;
  sessions: Array<{
    title: string;
    exercises: Array<{
      exercise: ExerciseReference;
      sets: number;
      reps: string;
      note?: string;
      _type: "planExercise";
      _key: string;
    }>;
    _type: "session";
    _key: string;
  }>;
};

export type Exercise = {
  _id: string;
  _type: "exercise";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  muscleGroup:
    "faetur" | "bak" | "bringa" | "axlir" | "handleggir" | "kjarni" | "allur";
  cue?: string;
  videoUrl?: string;
};

export type SiteContent = {
  _id: string;
  _type: "siteContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    headline: string;
    emphasis: string;
    sub: string;
    primaryCtaLabel: string;
    secondaryCtaLabel: string;
  };
  offeringsTitle: string;
  offeringsLead: string;
  offerings: Array<{
    name: string;
    tag: string;
    price: string;
    summary: string;
    features: Array<string>;
    featured?: boolean;
    _type: "offering";
    _key: string;
  }>;
  method?: {
    title: string;
    intro: string;
    steps: Array<{
      n: string;
      title: string;
      body: string;
      _type: "step";
      _key: string;
    }>;
  };
  forDads?: {
    title: string;
    points: Array<string>;
  };
  coachIntro?: {
    title: string;
    paragraphs: Array<string>;
  };
  faqTitle: string;
  faq: Array<{
    q: string;
    a: string;
    _type: "faqItem";
    _key: string;
  }>;
  finalCta?: {
    title: string;
    body: string;
    ctaLabel: string;
  };
  general?: {
    tagline: string;
    description: string;
  };
  contact?: {
    email: string;
    phone?: string;
    city?: string;
  };
  coach?: {
    name: string;
    role: string;
    bio: string;
    credentials?: string;
  };
  social?: {
    instagram?: string;
    facebook?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Article
  | Slug
  | ExerciseReference
  | TrainingPlan
  | Exercise
  | SiteContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../innri/app/lib/sanity.server.ts
// Variable: planByGoalAndFrequencyQuery
// Query: *[_type == "trainingPlan" && goal == $goal && sessionsPerWeek == $sessionsPerWeek][0]{    _id,    title,    goal,    sessionsPerWeek,    intro,    sessions[]{      _key,      title,      exercises[]{        _key,        sets,        reps,        note,        "exercise": exercise->{ _id, name, cue, videoUrl, muscleGroup }      }    }  }
export type PlanByGoalAndFrequencyQueryResult = {
  _id: string;
  title: string;
  goal: "fitutap" | "vodvauppbygging";
  sessionsPerWeek: 1 | 2 | 3 | 4 | 5;
  intro: string | null;
  sessions: Array<{
    _key: string;
    title: string;
    exercises: Array<{
      _key: string;
      sets: number;
      reps: string;
      note: string | null;
      exercise: {
        _id: string;
        name: string;
        cue: string | null;
        videoUrl: string | null;
        muscleGroup:
          | "allur"
          | "axlir"
          | "bak"
          | "bringa"
          | "faetur"
          | "handleggir"
          | "kjarni";
      };
    }>;
  }>;
} | null;

// Source: ../innri/app/lib/sanity.server.ts
// Variable: availableFrequenciesQuery
// Query: array::unique(*[_type == "trainingPlan" && goal == $goal].sessionsPerWeek) | order(@ asc)
export type AvailableFrequenciesQueryResult = Array<1 | 2 | 3 | 4 | 5>;

// Source: ../innri/app/lib/sanity.server.ts
// Variable: articlesQuery
// Query: *[_type == "article"] | order(title asc){    _id,    title,    "slug": slug.current,    category,    excerpt  }
export type ArticlesQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  category:
    "ad-byrja" | "ad-halda-afram" | "endurheimt" | "matarraedi" | "taekni";
  excerpt: string;
}>;

// Source: ../innri/app/lib/sanity.server.ts
// Variable: articleBySlugQuery
// Query: *[_type == "article" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    category,    excerpt,    body  }
export type ArticleBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  category:
    "ad-byrja" | "ad-halda-afram" | "endurheimt" | "matarraedi" | "taekni";
  excerpt: string;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "trainingPlan" && goal == $goal && sessionsPerWeek == $sessionsPerWeek][0]{\n    _id,\n    title,\n    goal,\n    sessionsPerWeek,\n    intro,\n    sessions[]{\n      _key,\n      title,\n      exercises[]{\n        _key,\n        sets,\n        reps,\n        note,\n        "exercise": exercise->{ _id, name, cue, videoUrl, muscleGroup }\n      }\n    }\n  }\n': PlanByGoalAndFrequencyQueryResult;
    '\n  array::unique(*[_type == "trainingPlan" && goal == $goal].sessionsPerWeek) | order(@ asc)\n': AvailableFrequenciesQueryResult;
    '\n  *[_type == "article"] | order(title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    category,\n    excerpt\n  }\n': ArticlesQueryResult;
    '\n  *[_type == "article" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    category,\n    excerpt,\n    body\n  }\n': ArticleBySlugQueryResult;
  }
}
